name: Check commits
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ESLint
        run: yarn
      - name: Run ESLint
        run: eslint --ext .js .
