name: Promote versioned released
on:
  release:
    types: released
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./.github/workflows/scripts/promote_tag.sh
        shell: bash
